### ISSUE TITLE
Úprava Rule clipboard

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#11]
Změna práce s Rule clipboard - stránkování atd... (nejdřív návrh)

blokováno #6

**Comment by vojir** [comment]
pro odebrání pravidla z Rule Clipboard využijte funkci "unmarkFoundRule", která je v FRManageru

**Comment by vojir** [comment]
až budete řešit paginator, v Moomlu (v souboru UITemplateRegistrator.js) jsou definované šablony "linksPaginator" a "selectPaginator", výběr typu paginatoru necháme posléze na uživateli, aktuálně je jeho výběr definovaný v config.js

**Comment by PreVaDu** [comment]
Rule clipboard je již plně funkční kromě řazení dle IM (server vrací chybu). Může se testovat.
Z plánovaného chybí přidat pouze rozbalování úloh...

**Comment by vojir** [comment]
ještě 2 drobnosti
- při přidávání pravidel z výsledků do rule clipboard bychom měli danou úlohu rozbalit (pokud je minimalizovaná)
- u minimalizovaných úloh zobrazme akční odkazy, které pracují s celou úlohou (aktuálně je tam jen "Task details", ale časem přibudou další)

**Comment by PreVaDu** [comment]
obě připomínky zpracovány

**Comment by PreVaDu** [comment]
Nevím, zda je aktuální stav, kdy načítám pravidla při každém výběru stránky znovu, správný, zda je nemám ukládat a volat jen při změně. Takže nevím, zda je možno uzavírat. Na druhou stranu ale pak nezbývá moc možností, jak zjistit, zda se v úloze něco změnilo.

**Comment by PreVaDu** [comment]
Ještě jedna poznámka - stránkování v discovered rules se vždy znovu renderuje při změně stránky, u rule clipboard jsem to pořešil jednoduchým přidáním active třídy pomocí JS a připadá mi to lepší. Časem se může sjednotit.

**Comment by vojir** [comment]
Při přidání nové úlohy do Rule clipboard (při přidání nalezeného pravidla z Discovered rules) by měla být daná úloha přidána na začátek seznamu, ne na jeho konec.

**Comment by PreVaDu** [comment]
Upraveno, napadlo mě to již při vývoji, ale po neúspěšném hledání řešení jsem na to zapomněl. Nyní by to mělo být v pořádku.
