### ISSUE TITLE
Nefunguje zadání atributu s hodnotou "subset" u atributu s 1 hodnotou

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#18]
Pokud má atribut pouze jednu hodnotu, skončí zadávání nesmyslným stavem. Optimálně by subset vůbec neměl být v nabídce.

**Comment by vojir** [comment]
Aktuálně tam nevidím žádnou změnu oproti původnímu chování :(
![screen](https://cloud.githubusercontent.com/assets/3865942/5596948/34b0527e-929a-11e4-9ed6-29a53538179e.png)

**Comment by PreVaDu** [comment]
Čekal jsem na odpověď. Chápu tedy jako souhlas a změny jsou nasazeny. Pro přidání i editování atributu.

**Comment by vojir** [comment]
OK, vypadá, že funguje..
