### ISSUE TITLE
Blokace starých IE

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#23]
Při přístupu přes starý Internet Explorer (9 a starší) zablokujeme přístup do aplikace a zobrazíme hlášku o nutnosti použít novější verzi, nebo alternativní prohlížeč.

**Comment by PreVaDu** [comment]
Browser detector byl již dříve detekován a varoval před IE < 9. Toto jsem zvýšil na starší než 10 a podobně jsem zvýšil i verze pro FF a Chrome dle běžné podpory CSS3 http://fmbip.com/litmus/ .
IE11 se pomocí této kontroly nedá rozpoznat, jelikož se změnil User-Agent (http://stackoverflow.com/questions/17447373/how-can-i-target-only-internet-explorer-11-with-javascript). My to však nepotřebujeme. Pokud bychom to chtěli řešit, možná by pomohl upgrade Mootools Core na poslední 1.5.1 verzi (minimálně u třídy BrowserDetector by muselo dojít k částečnému přepisu kvůli dále nepodporovaným vlastnostem).

Momentálně je tedy zobrazena hláška, že není podporován a že se doporučuje použít novější verze prohlížeč. Má-li dojít k blokování, v jaké části to uděláme, jakým způsobem (dialog, jak jsme se bavili?) a stopneme tím načítání zbytku, nebo to načteme pod neklikatelnou vrstvou? Nebylo by vhodné tuto kontrolu provádět už při login stránce, aby se uživatel zbytečně nepřihlašoval dvakrát?

**Comment by vojir** [comment]
Aktuálně se hláška o starém prohlížeči nikde nezobrazuje. Zobrazte ji prosím formou dialogu - který uživatel bude sice moct zavřít, ale bude dostatečně zřejmé, že ji četl.
Kontrola by neměla být úplně striktní, protože se může stát, že má uživatel jen chybně detekovanou identifikaci prohlížeče.
Kontrolu budeme aktuálně dělat jen pro dolovací UI, ostatní části systému by měly +- fungovat i s IE9, FF 4 atp.

**Comment by PreVaDu** [comment]
Zobrazovalo, testoval jsem na Win Vista s IE9. Ale předělal jsem to na dialog s odkazem, na který musí kliknout, aby to zmizelo. Opět testováno na Win Vista s IE9.
