### ISSUE TITLE
Vybrání pole antecedent/consequent v dialogu pro cíl přidání atributu

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#24]
U dialogu pro výběr cíle, kam má být přidán atribut po kliknutí na "+", by měl být vybrán select antecendent/consequent a měl by fungovat enter pro potvrzení (výrazně to urychlí práci s klávesnicí).

**Comment by PreVaDu** [comment]
Přidal jsem focus nejen pro výběr cíle, ale i pro výběr mergining typu. Tím lze celé přidání ovládat klávesnicí. Enter mi po přídání focusu funguje automaticky.

**Comment by vojir** [comment]
doplňte prosím možnost odeslání entrem

**Comment by PreVaDu** [comment]
Přidal jsem odeslání entrem pouze pro hlavní dialog výběru, při přidání a editaci atributu se objevovaly chyby a tak jsem to odložil na jindy (má-li se tato funkcionalita vůbec přidávat).

**Comment by vojir** [comment]
pro ostatní dialogy to není nutné - stejně se u nich předpokládá vyplnění dalších hodnot
