### ISSUE TITLE
Uspořádání attributes a data fields dle abecedy

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#29]
Atributy a data fields by měly být ve svých paletách uspořádány podle abecedy (s respektováním přesunu použitých položek na konec seznamu). Tj. k současnému stavu by mělo přibýt uspořádání zvlášť nepoužitých a zvlášť použitých položek.

**Comment by PreVaDu** [comment]
Hotovo.
U atributů prosím o řazení při prvotním načtení z DB, bude to lepší, jak přidávat další JS jen pro načtení.
Oba seznamy (used a unused) jsou řazeny zvlášť. Když jsem je řadil před oddělením used, tak mi to při animacích zůstávalo chvíli chaotické. Fce by to měla být docela rychlá, ale uvidíme v reálu, jak se při velkém množství atributů osvědčí...

Datafields řadím rovnou při renderingu v UIPainteru. Nenašel jsem, jestli dochází k přesunu jako u atributů a momentálně nefunguje přidání do atributů, hlásí to chybu 500...

**Comment by vojir** [comment]
výchozí seřazení vyřešeno na straně EasyMinerCenter
