### ISSUE TITLE
Možnost odstranění atributu z antecedentu či consequentu jejich vrácením zpět na paletu

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#30]
Doplňte prosím do aplikace jako další možný drop-cíl při přetažení atributu z antecedentu či consequentu pravidla jeho "vrácení" zpět na paletu. U daného atributu se tedy vykoná stejná akce, jako při kliknutí na "mazací křížek".

**Comment by PreVaDu** [comment]
Zprovozněno přidáním nového dragu v rámci jednoho mousedownu (dle konzultace).
