### ISSUE TITLE
Podpora přejmenování úlohy z "Discovered Rules"

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#31]

**Comment by vojir** [comment]
nefunguje editace názvu úlohy

**Comment by vojir** [comment]
Nefunguje editace v inputu pro zadání nového názvu úlohy

**Comment by PreVaDu** [comment]
Styly mají pro všechno (*) definování -moz-user-select: none; - má to takto zůstat a mám definovat vyjímku pouze pro dané inputy?

**Comment by vojir** [comment]
zákaz user-select nechte platný pro všechno vyjma inputů, u kterých se očekává editovatelnost

**Comment by PreVaDu** [comment]
hotovo
