### ISSUE TITLE
Povolení výběru pravidel z výsledků a z rule clipboard

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#37]
Povolte prosím výběr textového obsahu pravidel a měr zajímavosti z discovered rules a rule clipboard. Studentům to usnadní tvorbu analytických zpráv.

**Comment by PreVaDu** [comment]
Hotovo, povolil jsem to jen obsahové části...

**Comment by vojir** [comment]
bezva :+1:
