### ISSUE TITLE
Omezit počet zobrazených odkazů u stránkovače

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#41]
- pokud je hodně výsledků, je zobrazeno příliš mnoho položek v rámci stránkovače (měl by se zobrazovat menší počet odkazů na stránky v okolí té, která je aktuálně zobrazena)

**Comment by PreVaDu** [comment]
Při zobrazení pravidel a kliknutí znovu na 1. stránku se krásné zkrácení "ztratí"...
Změny šablony paginatoru by se měly projevit i v rule clipboard, pouze za předpokladu, že se bude "zkrácená varianta" zobrazovat i u menšího počtu stránek než 8, je to třeba upravit v MarkedTask...

Na druhou stranu si myslím, že toto zkracování má smysl u více jak 10 stránek, protože do deseti je to v pohodě...

![strankovani](https://cloud.githubusercontent.com/assets/7348640/6360511/e00805cc-bc7a-11e4-880c-7ee193deb5ed.jpg)

**Comment by vojir** [comment]
- výpočty stránek, které mají být aktuálně zobrazeny, byly opraveny
- byla vrácena přesunu části akcí do listeneru (není možná z důvodu možnost volby typu stránkovače)

**Comment by PreVaDu** [comment]
Navrhuji se k řešení listenerů stránkováče v budoucnu při vývoji vrátit, myslím, že to má řešení při zachování rozdělení na listenery/paintery/templatery a bylo by to i vhodné.
