### ISSUE TITLE
Problém s filtrovacími poli u atributů a data fields

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#43]
- při zobrazení filtrovacího pole po kliknutí na lupu by měl být vybrán obsah pole s filtrem, případně by měl být nastaven do daného pole focus
- při použití pomocných kláves na daném poli dojde k zablokování vstupu z klávesnice (např. při stisku klávesy home) - NUTNO OPRAVIT

**Comment by vojir** [comment]
při kliknutí na odkaz "Reset filter" by se mělo skrýt filtrovací pole

**Comment by PreVaDu** [comment]
Blokace přístupu byla dána user-selectem, který potom FF nějak divně vyhodnocoval, nesouviselo to vůbec s listenerem klávesnice.
Každopádně všechny požadované změny provedeny.

**Comment by vojir** [comment]
Potvrzuji, že funguje.
