### ISSUE TITLE
Problém s vykreslováním stránkovače v RuleClipboard

### ISSUE THREAD

**Issue by vojir** [KIZI/EasyMiner-EasyMiner2#44]
Při překreslení stránkovače v RuleClipboard nejsou korektně vykreslovány posuny odkazů 

![err](https://cloud.githubusercontent.com/assets/3865942/6321789/063d0af6-bb06-11e4-8c20-3ec24ca4179f.png)

**Comment by vojir** [comment]
![err2](https://cloud.githubusercontent.com/assets/3865942/6321799/4ab4bdc8-bb06-11e4-8c0b-64d39e16a6e9.png)

**Comment by PreVaDu** [comment]
V discovered rules to bylo v pořádku?

**Comment by vojir** [comment]
dle testování se to týká rule clipboard

**Comment by PreVaDu** [comment]
Stránkování obsahuje více chyb - u neaktivní úlohy se stránkování nerenderuje při rozbalení, je třeba změnit počet pravidel na stránku, pak se to překreslí... Řešení mám vymyšlené, jen není nasazené, viz níže.

Šablona paginator je nastavena na to, že "zkracuje" při více jak 7 stránkách v úloze, je to tak? Přidám tedy při tomto počtu překreslování hlavičky, jinak jsem ho u rule clipboard nedával při každém kliknutí, protože mi to přišlo zbytečné... Celkově to doladíme při sjednocení found a marked rules.

Každopádně, nemohu upravit některé soubory, mají špatná práva na FTP, zejména MarkedTask, MarkedRule, MRManager apod., prosím o zpřístupnění, pak mohu pokračovat s úpravami.

**Comment by PreVaDu** [comment]
Je to opraveno, i nově nalezená chyba. Stránkování se znovu renderuje při každé změně stránky pouze za předpokladu, že má úloha více jak 7 stránek. Pokud se to v rámci #41 změní, mělo by se to promítnout do kódu. Více v #41.
